### ISSUE TITLE
下書きプレビュー用の URL を自動的に発行して欲しい

### ISSUE THREAD

**Issue by okkez** [hatena/Hatena-Blog-Workflows-Boilerplate#11]
便利は boilerplate の公開ありがとうございます。

はてなアカウントを持っていない人でも簡単に書き始められそうだったので、社のテックブログの運用フローに組み込んでみました。

ブログオーナー以外のアカウントでも下書きページからプレビュー用の URL を発行できることはわかったのですが、毎回ブラウザアクセスして発行するのが面倒です。
プレビュー用 URL を発行する API がないか調べてみたのですが、見つからず。。。

下書きプレビュー用の URL を自動的に発行して PR の description に書き込んでくれるようになると大変便利だと思うので、機能の追加をお願いしたいです。

**Comment by airreader** [comment]
ご利用、ご要望いただきありがとうございます！
こちらは弊社内でも課題に感じている点でした。対応を検討させていただきます。

**Comment by airreader** [comment]
こちら、Workflowに組み込む前段として、APIから下書きプレビューURLを発行できるように機能追加を行いました。

[AtomPub APIから下書きプレビュー共有用URLを発行できるようにしました - はてなブログ開発ブログ](https://staff.hatenablog.com/entry/2023/10/16/102131)

続いて、Workflowへの組み込みを検討していまいります。

**Comment by Songmu** [comment]
当ワークフロー内部で使っているツールのblogsync v0.17.0 でプレビューURLに対応しました。連携しやすくなっていると嬉しいです。

https://github.com/x-motemen/blogsync/pull/104

**Comment by airreader** [comment]
はてなブログ側で使っている blogsyncのバージョン指定を変更し、記事のメタデータ領域にプレビューURLが含まれるようになりました。ご要望いただきありがとうございました。

また blogsync の素早い対応ありがとうございました。

**Comment by airreader** [comment]
https://staff.hatenablog.com/entry/2023/10/30/110546
こちら対応を告知いたしました。
また、PullRequestにも下書きプレビュー共有URLが含まれていたほうが便利かと思いますので、編集画面URLとともに含める変更を入れています。
