### ISSUE TITLE
独自ドメイン利用時に workflow に設定すべきドメインが不定

### ISSUE THREAD

**Issue by hsbt** [hatena/Hatena-Blog-Workflows-Boilerplate#15]
独自ドメインとして `tech.andpad.co.jp` を利用しています。その際に `pull-draft.yaml` アクションは以下の設定でのみ動作し

* BLOG_DOMAIN: tech.andpad.co.jp
* blogsync.yaml のドメイン: tech.andpad.co.jp

`push-draft.yaml` アクションは以下の設定でのみ動作するようです。

* BLOG_DOMAIN: xxx.hatenablog.com
* blogsync.yaml のドメイン: xxx.hatenablog.com

xxx は弊社で作成したブログのサブドメインです。

追記: エラー内容

`pull-draft.yaml` に `xxx.hatenablog.com` を設定したときのエラーログは以下のとおりです。

```
Run hatena/hatenablog-workflows/.github/actions/pull-draft-by-title@v1
Run blogsync pull xxx.hatenablog.com
     error blog not found: xxx.hatenablog.com
```

`push-draft.yaml` に `tech.andpad.co.jp` を指定したときのエラーログは以下のとおりです。

```
Run for file in draft_entries/6801883189050105273.md; do
(snip)
  error cannot find blog for draft_entries/6801883189050105273.md
```

**Comment by hsbt** [comment]
特に設定に独自ドメインを使いたい、ということはなく`tech.andpad.co.jp` でも `xxx.hatenablog.com` でも同じ設定で動けばユースケースとしては問題ありません。

**Comment by airreader** [comment]
こちら以下のパターンで動作確認をしたのですが、特に動作上の問題が確認できませんでした。

- 独自ドメインを利用しているブログ
- BLOG_DOMAIN と blogsync.yaml に独自ドメインを設定する
- 下書きの新規作成 `create-draft.yaml`
- 既存下書きの取得 `pull-draft.yaml`

ブログの仕組み上は、独自ドメインを設定している場合、AtomPubAPIのエンドポイントは 独自ドメインでも独自ドメイン設定前のブログのドメインでもどちらでも受け付けますので、それ以外のところでなにか問題が発生しているようです。

ちなみに、BLOG_DOMAIN と blogsync.yaml に独自ドメインを設定した上で、`create draft`アクションは実行可能でしょうか？お手数をおかけしますが、ご確認いただければと思います。 @hsbt

**Comment by hsbt** [comment]
`push-draft.yaml` はどうでしょうか? この workflow が独自ドメイン設定で動かない、というのが報告内容になります。

**Comment by airreader** [comment]
なるほど！独自ドメインをBLOG_DOMAINなどに設定した場合、下書きを更新した際の `push-draft.yml` 確かに失敗しました。失礼いたしました。
こちらまた調べてみますので、お待ち下さい。

**Comment by airreader** [comment]
初期のはてなブログドメインをBLOG_DOMAINなどに設定した状態で `pull-draft.yaml` を実行した際のエラーの内容をいただけないでしょうか？こちら再現できておらずでして…。

**Comment by hsbt** [comment]
@airreader ほぼ情報はありませんが、以下のようなログで落ちていました。

```
Run hatena/hatenablog-workflows/.github/actions/pull-draft-by-title@v1
Run blogsync pull xxx.hatenablog.com
     error blog not found: xxx.hatenablog.com
```

**Comment by airreader** [comment]
ありがとうございました。

BLOG_DOMAINやyamlに独自ドメインを設定している場合に `push-draft.yaml` に失敗する件につきましては、workflow内で利用しているblogsync内で発生しているエラーのようでした。yamlのドメイン設定とEditURLに含まれるドメインに差異がある場合に発生するようです。
https://github.com/x-motemen/blogsync/blob/master/entry.go#L55

BLOG_DOMAINやyamlに初期のブログドメインを設定している場合に`pull-draft.yaml` に失敗する件につきましては、再現はできませんでしたがBLOG_DOMAIN にのみ独自ドメインのURLが登録されている場合に同様のエラーが出ることを確認できました。blogsync側のコードも確認したところBLOG_DOMAINとyamlの設定に差異がある場合にエラーが発生するようでした。

つきましては、お手数ですがBLOG_DOMAINとblogsync.yamlに初期はてなブログドメインを設定した上で、再度 pull-draft をお試しいただけないでしょうか。  @hsbt 
ただ、既存の設定に独自ドメインを指定されている場合、エントリが保存されるディレクトリが変更されますので、ご注意いただけますと幸いです。お手数をおかけして誠に申し訳ございません。

AtomPubAPIのエンドポイントは、独自ドメインでも動作しますが、変更されうるため、初期はてなブログドメインを正として取り扱います。そのように設定していただけると幸いです。(ブログの詳細設定「ルートエンドポイント」でも初期のはてなブログドメインが指定されています)
設定ドキュメントでは記載が不足していたので書き足させていただきます。

**Comment by hsbt** [comment]
>つきましては、お手数ですがBLOG_DOMAINとblogsync.yamlに初期はてなブログドメインを設定した上で、再度 pull-draft をお試しいただけないでしょうか。 @hsbt

調査ありがとうございます。上記に書いたエラーと同じ条件のため、同じエラーで取得できませんでした。折りたたみ箇所を展開したログを貼ります。

```
Run hatena/hatenablog-workflows/.github/actions/pull-draft-by-title@v1
  with:
    title: GitHub Sync のテスト
    BLOG_DOMAIN: xxx.hatenablog.com
  
  env:
    BLOGSYNC_PASSWORD: ***
Run blogsync pull xxx.hatenablog.com
  blogsync pull xxx.hatenablog.com
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BLOGSYNC_PASSWORD: ***
     error blog not found: xxx.hatenablog.com
Error: Process completed with exit code 1.
```

もし、試行に際して不足している、勘違いしている箇所があれば教えてもらえるとありがたいです。@onk さんにはラフにお伝えしましたが、Meet などで画面をお見せしながら実行することも可能なのでご連絡ください。

**Comment by airreader** [comment]
ありがとうございます！やはり失敗するのですね…。今のところ、原因や手がかりを思いついていないのですが、今回お渡しいただいたログで気になる点がありました。

以下は独自ドメイン利用で、pullに成功しているログですが、4行目の `BLOG_DOMAIN: xxx.hatenablog.com` の次に空行がありません。一方、ご連絡いただいたログでは空行があります。
```
Run hatena/hatenablog-workflows/.github/actions/pull-draft-by-title@v1
  with:
    title: 下書き日記2
    BLOG_DOMAIN: xxx.hatenablog.com
  env:
    BLOGSYNC_PASSWORD: ***
Run blogsync pull xxx.hatenablog.com
  blogsync pull xxx.hatenablog.com
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BLOGSYNC_PASSWORD: ***
       GET ---> https://blog.hatena.ne.jp/AirReader/xxx.hatenablog.com/atom/entry
```
まだ、詳しい調査はできていないのですが、 `BLOG_DOMAIN` 設定に改行を含めるとご連絡いただいたログが出力され失敗することは確認いたしました。
つきましては、`BLOG_DOMAIN` 設定に改行が含まれていないかだけご確認いただけないでしょうか？
度々お手数をおかけいたしますがお願い致します。

**Comment by hsbt** [comment]
>つきましては、BLOG_DOMAIN 設定に改行が含まれていないかだけご確認いただけないでしょうか？

`BLOG_DOMAIN` から改行を消したところ動きました。以前に Secrets を入れるときに改行を入れなければ動かないけーすもあったため、常に改行を入れるようにしていたのが原因だったようです。

一旦報告した内容については

* 初期はてなブログドメインを設定して利用する
* `BLOG_DOMAIN` には改行を入れない

で解決できそうでした。調査ありがとうございます。

テンプレートや blogsync の方で、上記を意識しなくても動くようになると後に続く利用者がハマることはないかもしれない、と感じたので対応があるとよいかもしれません。

**Comment by airreader** [comment]
動作したとのこと良かったです。
ドメイン前後のホワイトスペースは処理過程で除去すべきだと思いますので、別途対応を検討します。ありがとうございました。

**Comment by hsbt** [comment]
問題としては解決したので issue はクローズします。引き続き活用していこうと思います!

**Comment by airreader** [comment]
issue化しました
https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/issues/16
https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/issues/17
