### ISSUE TITLE
BLOG_DOMAIN の前後にスペースや改行が含まれていると正常に動作しない

### ISSUE THREAD

**Issue by airreader** [hatena/Hatena-Blog-Workflows-Boilerplate#16]
末尾スペースや改行が混入していてもユーザーは気づきにくく、対処がしにくい。
処理過程でホワイトスペースを除去したい

**Comment by halkt** [comment]
- https://github.com/hatena/hatenablog-workflows/pull/36 で対応したのでクローズします
