### ISSUE TITLE
はてなブログ上で直接編集を行ったエントリーが pull draft 実行時に削除されてしまう

### ISSUE THREAD

**Issue by hsbt** [hatena/Hatena-Blog-Workflows-Boilerplate#21]
以下の手順で `entries` に存在する公開済みのエントリが `pull-draft.yaml` 実行時に削除されてしまう現象が発生しています。

1. `pull.yaml` を実行して公開済みのエントリを `entries` に保存
2. はてなブログのダッシュボード経由で公開済みエントリを修正
3. `pull-draft.yaml` 実行時に 2 で修正したエントリが `entries` から削除される

2 の公開済みエントリの修正は原則 GitHub の PR で実行しているつもりでしたが、気が付かないうちに編集権限を持ったメンバーが修正していたようです。

あくまでも状況的に、消えてしまうエントリと、公開済みのエントリを定期的に同期したときに差分が発生したエントリが一致していたので上記の様な報告となっていますが、実際の原因は別の箇所にもあるかもしれません。

3 の実行時に削除ではなく当該エントリについては何もしないようになるとありがたいです。

※ 発生している状況について画面など交えて共有することも可能なので、もう少し詳しい情報が必要な場合はご連絡ください。

**Comment by theoremoon** [comment]
お知らせありがとうございます。確かにpull-draftの実行時に意図しないdiffがあるとそのファイルは削除されてしまうフローになっていますね（メモ：[このあたり](https://github.com/hatena/hatenablog-workflows/blob/b8bf9264246c0e358251227465bf4c1c88effd87/.github/actions/create-draft-pull-request/action.yaml#L32-L35)）。ここはワークフローを修正して対処しようと思いますので対応をお待ち下さい

**Comment by hsbt** [comment]
https://github.com/hatena/hatenablog-workflows/releases/tag/v1.2.7 で対応いただいたので close します。ありがとうございました。

**Comment by halkt** [comment]
@hsbt 
すみません、こちらまだ修正できていなくて対応中になりますのでissueはReopenさせていただきます。
修正ができ次第、こちらで閉じさせていただきますので少々お待ち下さい。

**Comment by hsbt** [comment]
おっと失礼しました 🙏

**Comment by hsbt** [comment]
❤️ ありがとうございます。
