### ISSUE TITLE
README.mdにpushコマンドの記載

### ISSUE THREAD

**Issue by Pregum** [hatena/Hatena-Blog-Workflows-Boilerplate#24]
便利なtemplateを作成いただき、ありがとうございます。

1点ご要望です。

* 普段GitHubを使用している方であれば問題ないかと思いますが、[README.mdのセットアップ](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate#%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97) の下記項目に沿って進めていますと、GitHub上にpushされないまま手順を進められる方がいるかなと感じました。

```md
2. blogsync.yamlの各種項目を記述してください
// :
3. GitHub リポジトリの設定 「Secrets and variables > actions > Repository variables」 から以下のVariableを登録する
```

以下のどちらかの対応をして頂けますと、GitHubに慣れていない方でもスムーズに進められると感じましたのでIssueを立てました。

- 2.の項目にGitHubへpushする旨を記載
- GitHub上で操作する場合はその旨をセットアップの章に記載

もしこちらで変更する方がよろしければ、指示して頂けますと嬉しいです！

ご検討のほど、よろしくお願いいたします🙏

**Comment by airreader** [comment]
ありがとうございます！確かにmainブランチに反映することまで書いていなかったので書いてあったほうが親切そうですね。
修正検討します。

**Comment by airreader** [comment]
修正を反映しましたのでこちら閉じさせていただきます！

**Comment by Pregum** [comment]
@airreader 

迅速なご対応ありがとうございます 🙏
