### ISSUE TITLE
`create-draft.yaml` を使って下書き作成する際、 Title にハッシュタグを含めるとハッシュタグ以降の文字が記事タイトルから消えてしまう

### ISSUE THREAD

**Issue by stefafafan** [hatena/Hatena-Blog-Workflows-Boilerplate#26]
## ユースケース
[Fukuoka.go #19 Reboot に参加した #fukuokago - stefafafan の fa は3つです](https://blog.stenyan.jp/entry/2023/12/19/201809) のように、記事タイトルにイベントのハッシュタグを含めてシェア時に自然と届けたい層に届くようにしたいことがあります。

## 事象
`create-draft.yml` のworkflow_dispatch で Title に `これはテストです #test` をセットしてみたところ、
生成された md ファイルのタイトルは `Title: これはテストです` に変わっていました。 (`#test` が消えます。)
https://github.com/stefafafan/blog.stenyan.jp/pull/8

なお、workflow_dispatchで指定するTitleにおいて自分で `''` を使って囲うことによって回避することはできました（代わりにP-Rのタイトルも `''` が入るので一瞬ちょっと不安になりますが）。
https://github.com/stefafafan/blog.stenyan.jp/pull/9

## 希望する挙動
workflow_dispatch の Title で指定した内容について、適宜記号などはエスケープされ、指定した内容そのままが記事タイトルに反映されてほしいと思っています。

ご検討のほどよろしくお願いします！

**Comment by airreader** [comment]
ありがとうございます！
指定したタイトルが異なるタイトルとして投稿されるのは問題ですので対応を検討します。

**Comment by halkt** [comment]
@stefafafan 

連絡ありがとうございます!
こちらは https://github.com/hatena/hatenablog-workflows/pull/52 で解消されましたので閉じます!

**Comment by stefafafan** [comment]
ありがとうございます！！
