### ISSUE TITLE
画像アップロード機能が動作しない

### ISSUE THREAD

**Issue by chaspy** [hatena/Hatena-Blog-Workflows-Boilerplate#33]
いつもお世話になっております。便利に使わせていただいています。

https://staff.hatenablog.com/entry/2024/04/09/150204 の記事で案内されている画像アップロード機能が期待通り動いていないため、支援いただけると嬉しいです。

# やったこと・起きていること
- [こちら](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate?tab=readme-ov-file#boilerplate%E3%81%AB%E6%96%B0%E3%81%97%E3%81%8F%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%81%9Fworkflow%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B) のスクリプトを実行
- 以下の差分が生成される

![CleanShot 2024-04-11 at 14 42 50](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/333b8559-baeb-4139-8044-8b8503323e3d)

- `create draft` の workflow からテスト用の記事を作成
- markdown と画像を追加する
![CleanShot 2024-04-11 at 14 44 04](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/8eb66667-b5ba-4b93-b249-34973ce6c5be)
![CleanShot 2024-04-11 at 14 44 26](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/e9719344-3a1e-4216-998b-52fa9620aba2)

- はてなのプレビューでは変換されていない
![CleanShot 2024-04-11 at 14 45 00](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/4c303a2f-2628-401b-bdb2-f0922d22b394)

# 調べたこと
動いている workflow

![CleanShot 2024-04-11 at 14 46 29](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/4ea4cc01-4ba0-4cd5-be0d-277789493561)

`push draft to hatena blog / push-draft / upload-images / upload-image (pull_request) ` だと思うのでログを見る

この辺りの処理な気がしますが、ここから先は追ってないです。

![CleanShot 2024-04-11 at 14 47 29](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/4e91646c-8be9-4cd4-a96a-eb6d45056eaa)

画像アップロードと変換処理が発火する条件が何かありますでしょうか？

よろしくお願いします。

**Comment by chaspy** [comment]
こちら https://github.com/hatena/hatenablog-workflows/blob/51715f74ec57197e8033a099c5872e08f265239a/fotolife-client.py#L81-L84 の処理がうまく動いていないようです。` /path/img.jpg "title text"` というファイルを探そうとして、ないという判断になっていそう。

`![alt text](/path/img.jpg)` の形式ならうまく動くようなので、ブログの記事のサンプルを修正するか、スクリプトを修正した方が良いと思いました。

また、path 指定の場合、記事からの相対パスであることも見落としそう（repository root からの相対かと思ってしまいました）なので、そこもサンプルで捕捉できるとなお良い感じました。

検討よろしくお願いします。

![CleanShot 2024-04-11 at 15 00 32](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/cc1db9d8-234e-4d10-8172-f6716b78e607)
![CleanShot 2024-04-11 at 15 00 54](https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate/assets/10370988/e11d8e6d-030c-407d-b695-5b74c9767a3e)

**Comment by airreader** [comment]
フィードバックありがとうございます！！
一旦ブログ記事のサンプルの該当部分のパスの記述を修正し、説明を追加いたしました。
https://staff.hatenablog.com/entry/2024/04/09/150204
