### ISSUE TITLE
下書きをdraft pull requestとして作成したい

### ISSUE THREAD

**Issue by kymmt90** [hatena/Hatena-Blog-Workflows-Boilerplate#35]
記事の下書きを含むPRを[draft pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests)として作成したいです。

hatena/hatenablog-workflowsで利用しているpeter-evans/create-pull-requestには[inputとして`draft`を渡せる](https://github.com/peter-evans/create-pull-request/blob/v6/README.md?plain=1#L76)ので実現はできそうです。必要なときだけ`draft: true`が設定できればよいと思います。

## ユースケース

このテンプレートに基づいて所属企業のブログ執筆環境を運用しています。[CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)を用いて技術広報担当者をコードオーナーとして設定することで、記事が公開前に必ずレビューされるようにしています。

現在は、下書きを含むPRは必ずready for reviewとして作成されます（手動でdraftに戻せるのは戻せる）。この場合、PR作成時点でコードオーナーにレビュー依頼が必ず送信されます。執筆者側は執筆途中なので必ずしも記事をレビューできる状態ではない可能性がありますが、コードオーナーはレビュー依頼通知を受け取ってしまうという課題があります。

一方、PRをdraftとして作成すると、コードオーナーへのレビュー依頼送信を抑制できます。

> Draft pull requests cannot be merged, and code owners are not automatically requested to review draft pull requests.

これを利用して、執筆している間はdraft PRとし、記事公開前にready for reviewなPRに変更することで、レビュー可能であることを示しつつ、自動でコードオーナーにレビュー依頼を送信できます。

**Comment by airreader** [comment]
ご要望いただき、また詳しいユースケースも記載いただきありがとうございました。
多くの企業様ではレビューを前提に運用されているようですので、下書き作成時に Draft PR として作成されるのは望ましそうですね。
対応を検討いたします。

**Comment by airreader** [comment]
こちら、下書き作成時はDraft pull requestとして作成されるように仕様を変更し、以下で告知いたしました！
ご意見いただきありがとうございました！

[HatenaBlog Workflows Boilerplate で下書き記事を作成した際にドラフト状態のプルリクエストとして作成されるよう変更しました - はてなブログ開発ブログ](https://staff.hatenablog.com/entry/2024/06/25/163227)

**Comment by kymmt90** [comment]
迅速なご対応ありがとうございました！
