### ISSUE TITLE
画像アップロードの際にplainオプションを追加したい

### ISSUE THREAD

**Issue by hoshiminn** [hatena/Hatena-Blog-Workflows-Boilerplate#37]
画像パスの本文差し替え後のはてな記法の中に`plain`のオプションがなく、画像をクリックするとはてなフォトライフに飛ぶようになってしまいます。できればブラウザポップアップで見せられるようにしたいと思っております。

そのため、画像アップロードの際に`plain`がつけられるように選択できるたり、デフォルトでついていると嬉しいです。
ご検討よろしくお願いいたします。

**Comment by airreader** [comment]
@hoshiminn こちらplainが付加されるように対応いたしました。ありがとうございました！

**Comment by hoshiminn** [comment]
ご対応ありがとうございました！
